### ISSUE TITLE
Site is offline

### ISSUE THREAD

**Issue by Remourz** [Proviesec/Proviesec-Bug-Bounty-Dorking-Site-PBBDS#3]
Site give me an 404

**Comment by provie** [comment]
[https://proviesec.github.io/Proviesec-Bug-Bounty-Dorking-Site-PBBDS/](https://proviesec.github.io/Proviesec-Bug-Bounty-Dorking-Site-PBBDS/)

**Comment by provie** [comment]
I have change the link in the readme, thx
